import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import DateTime, ForeignKey, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, declared_attr, mapped_column
from sqlalchemy.sql import func


class UUIDPrimaryKeyMixin:
    """UUID v4 primary key, generated by Postgres (`gen_random_uuid()`, core
    since PG13 — no `pgcrypto` extension needed). Applies to every table in
    this project; do not introduce integer primary keys (see CLAUDE.md).
    """

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )


class TimestampMixin:
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )

    # `updated_at` is refreshed by the database (`onupdate=func.now()`), not
    # computed in Python — reading it back after an UPDATE would otherwise
    # require an implicit SELECT, which async SQLAlchemy cannot do lazily
    # (raises MissingGreenlet the moment a response schema touches the
    # attribute). `eager_defaults` appends a RETURNING clause to the UPDATE
    # itself instead, so the refreshed value is already loaded.
    @declared_attr.directive
    def __mapper_args__(cls) -> dict[str, Any]:
        return {"eager_defaults": True}


class TenantScopedMixin:
    """Adds the `organization_id` column every tenant-owned table must carry.

    Not used by `Organization` itself (the tenant root) or by genuinely
    global reference data (e.g. `Permission`). Every model using this mixin
    must also get a matching Row-Level Security policy in its Alembic
    migration — see `app/db/rls.py`.
    """

    organization_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("organizations.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )
