"""auth refresh tokens and phase 2 permissions

Revision ID: 679c8590af57
Revises: 8657da82d547
Create Date: 2026-09-11 17:22:16.513728

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.db.rls import disable_tenant_rls, enable_indirect_tenant_rls

# revision identifiers, used by Alembic.
revision: str = '679c8590af57'
down_revision: Union[str, None] = '8657da82d547'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Permission codes introduced by Phase 2's actual endpoints, and which
# system roles are granted each — see docs/architecture.md § 4. Deliberately
# minimal: only what the routes built in this phase actually check.
#   - SUPER_ADMIN manages organizations only (via /api/v1/admin/*).
#   - ORG_ADMIN manages users only within their own tenant (via
#     /api/v1/recruiter/users), enforced by RLS regardless.
# Neither role is granted the other's permissions — an ORG_ADMIN has no path
# to organization.* and SUPER_ADMIN has no path to user.* (the first
# ORG_ADMIN of a new org is created directly by organization_service as
# part of organization.create, not via a separate user.create check).
_PERMISSIONS = (
    ("organization.create", "Create a new organization (platform administration)."),
    ("organization.read", "List/view organizations (platform administration)."),
    ("user.create", "Create a user within one's own organization."),
    ("user.read", "View users within one's own organization."),
)
_ROLE_PERMISSIONS = {
    "SUPER_ADMIN": ("organization.create", "organization.read"),
    "ORG_ADMIN": ("user.create", "user.read"),
}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['replaced_by_id'], ['user_refresh_tokens.id'], name=op.f('fk_user_refresh_tokens_replaced_by_id_user_refresh_tokens'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_user_refresh_tokens_token_hash'))
    )
    op.create_index(op.f('ix_user_refresh_tokens_family_id'), 'user_refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_user_refresh_tokens_user_id'), 'user_refresh_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # `user_refresh_tokens` has no organization_id of its own — tenancy is
    # derived through user_id -> users.organization_id, same pattern as
    # user_roles (see app/models/user.py::UserRefreshToken).
    enable_indirect_tenant_rls(
        op,
        "user_refresh_tokens",
        exists_subquery=(
            "EXISTS (SELECT 1 FROM users u WHERE u.id = user_refresh_tokens.user_id "
            "AND u.organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)"
        ),
    )

    permissions_table = sa.table(
        "permissions",
        sa.column("id", sa.UUID()),
        sa.column("code", sa.String()),
        sa.column("description", sa.Text()),
    )
    permission_ids = {code: str(uuid.uuid4()) for code, _ in _PERMISSIONS}
    op.bulk_insert(
        permissions_table,
        [
            {"id": permission_ids[code], "code": code, "description": description}
            for code, description in _PERMISSIONS
        ],
    )

    connection = op.get_bind()
    role_ids = {
        name: row[0]
        for name in _ROLE_PERMISSIONS
        for row in connection.execute(
            sa.text("SELECT id FROM roles WHERE organization_id IS NULL AND name = :name"),
            {"name": name},
        )
    }

    role_permissions_table = sa.table(
        "role_permissions",
        sa.column("role_id", sa.UUID()),
        sa.column("permission_id", sa.UUID()),
    )
    op.bulk_insert(
        role_permissions_table,
        [
            {"role_id": role_ids[role_name], "permission_id": permission_ids[code]}
            for role_name, codes in _ROLE_PERMISSIONS.items()
            for code in codes
        ],
    )


def downgrade() -> None:
    connection = op.get_bind()
    connection.execute(
        sa.text(
            "DELETE FROM role_permissions WHERE permission_id IN "
            "(SELECT id FROM permissions WHERE code = ANY(:codes))"
        ),
        {"codes": [code for code, _ in _PERMISSIONS]},
    )
    connection.execute(
        sa.text("DELETE FROM permissions WHERE code = ANY(:codes)"),
        {"codes": [code for code, _ in _PERMISSIONS]},
    )

    disable_tenant_rls(op, "user_refresh_tokens")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_refresh_tokens_user_id'), table_name='user_refresh_tokens')
    op.drop_index(op.f('ix_user_refresh_tokens_family_id'), table_name='user_refresh_tokens')
    op.drop_table('user_refresh_tokens')
    # ### end Alembic commands ###
