"""identity and tenancy foundation

Revision ID: 8657da82d547
Revises:
Create Date: 2026-09-11 16:00:49.326916

"""

import uuid
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from app.db.rls import disable_tenant_rls, enable_indirect_tenant_rls, enable_tenant_rls
from app.models.rbac import SYSTEM_ROLES

# revision identifiers, used by Alembic.
revision: str = "8657da82d547"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "SUSPENDED", name="organization_status"),
            server_default="ACTIVE",
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
        sa.UniqueConstraint("slug", name=op.f("uq_organizations_slug")),
    )
    op.create_table(
        "permissions",
        sa.Column("code", sa.String(length=150), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_permissions")),
        sa.UniqueConstraint("code", name=op.f("uq_permissions_code")),
    )
    op.create_table(
        "roles",
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_system", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_roles_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
    )
    op.create_index(op.f("ix_roles_organization_id"), "roles", ["organization_id"], unique=False)
    op.create_index(
        "uq_roles_org_name",
        "roles",
        ["organization_id", "name"],
        unique=True,
        postgresql_where="organization_id IS NOT NULL",
    )
    op.create_index(
        "uq_roles_system_name",
        "roles",
        ["name"],
        unique=True,
        postgresql_where="organization_id IS NULL",
    )
    op.create_table(
        "users",
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_users_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_organization_id"), "users", ["organization_id"], unique=False)
    op.create_index(
        "uq_users_org_email",
        "users",
        ["organization_id", "email"],
        unique=True,
        postgresql_where="organization_id IS NOT NULL",
    )
    op.create_index(
        "uq_users_platform_email",
        "users",
        ["email"],
        unique=True,
        postgresql_where="organization_id IS NULL",
    )
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("permission_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
            name=op.f("fk_role_permissions_permission_id_permissions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name=op.f("fk_role_permissions_role_id_roles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("role_id", "permission_id", name=op.f("pk_role_permissions")),
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_user_roles_role_id_roles"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_roles_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id", name=op.f("pk_user_roles")),
    )
    # ### end Alembic commands ###

    # --- Row-Level Security: second enforcement layer per docs/security.md ---
    # `organizations` is the tenant root; its own id IS the tenant key.
    enable_tenant_rls(op, "organizations", org_column="id")
    # System roles (organization_id IS NULL) must stay visible to every
    # tenant; org-specific custom roles (future) are isolated normally.
    enable_tenant_rls(op, "roles", null_visible_to_all_tenants=True)
    # organization_id IS NULL on `users` means a platform-level SUPER_ADMIN
    # account — that must NOT be visible to ordinary tenant members, so this
    # does not set null_visible_to_all_tenants.
    enable_tenant_rls(op, "users")
    # `permissions` is global reference data (no organization_id) — no RLS.
    # Join tables have no organization_id of their own; tenancy is derived
    # through the row they point at.
    enable_indirect_tenant_rls(
        op,
        "role_permissions",
        exists_subquery=(
            "EXISTS (SELECT 1 FROM roles r WHERE r.id = role_permissions.role_id "
            "AND (r.organization_id IS NULL OR r.organization_id = "
            "NULLIF(current_setting('app.current_org_id', true), '')::uuid))"
        ),
    )
    enable_indirect_tenant_rls(
        op,
        "user_roles",
        exists_subquery=(
            "EXISTS (SELECT 1 FROM users u WHERE u.id = user_roles.user_id "
            "AND u.organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)"
        ),
    )

    # --- Seed data: the five system roles (docs/architecture.md § 4) ---
    roles_table = sa.table(
        "roles",
        sa.column("id", sa.UUID()),
        sa.column("organization_id", sa.UUID()),
        sa.column("name", sa.String()),
        sa.column("is_system", sa.Boolean()),
    )
    op.bulk_insert(
        roles_table,
        [
            {"id": str(uuid.uuid4()), "organization_id": None, "name": name, "is_system": True}
            for name in SYSTEM_ROLES
        ],
    )


def downgrade() -> None:
    disable_tenant_rls(op, "user_roles")
    disable_tenant_rls(op, "role_permissions")
    disable_tenant_rls(op, "users")
    disable_tenant_rls(op, "roles")
    disable_tenant_rls(op, "organizations")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_roles")
    op.drop_table("role_permissions")
    op.drop_index(
        "uq_users_platform_email", table_name="users", postgresql_where="organization_id IS NULL"
    )
    op.drop_index(
        "uq_users_org_email", table_name="users", postgresql_where="organization_id IS NOT NULL"
    )
    op.drop_index(op.f("ix_users_organization_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(
        "uq_roles_system_name", table_name="roles", postgresql_where="organization_id IS NULL"
    )
    op.drop_index(
        "uq_roles_org_name", table_name="roles", postgresql_where="organization_id IS NOT NULL"
    )
    op.drop_index(op.f("ix_roles_organization_id"), table_name="roles")
    op.drop_table("roles")
    op.drop_table("permissions")
    op.drop_table("organizations")
    # ### end Alembic commands ###

    # `drop_table` does not drop the native Postgres ENUM type backing the
    # `status` column — left alone, it orphans the type and a later
    # `upgrade` fails with "type already exists". Autogenerate does not add
    # this for us; it must be explicit.
    sa.Enum(name="organization_status").drop(op.get_bind(), checkfirst=True)
